### ISSUE TITLE
"Transaction Gas price too low. It does not satisfy your node's minimal gas price" error always prints 0 as the `minimal` price

### ISSUE THREAD

**Issue by dtran320** [paritytech/parity-ethereum#10348]
- **Parity Ethereum version**: 2.2.10
- **Operating system**: Linux
- **Installation**: one-line installer 
- **Fully synchronized**: yes
- **Network**: ethereum mainnet
- **Restarted**: yes

**Expected Behavior**
`eth_sendRawTransaction` with gas price of 5000000000 wei goes through or returns a different error message.

**Actual Behavior**
`eth_sendRawTransaction` returns
```json
{"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction gas price is too low. It does not satisfy your node's minimal gas price (minimal: 0, got: 5000000000). Try increasing the gas price."}
```

Checking the node's minimal gas price definitely returns `0x250e87c` or 38856828 wei, which is definitely still less than 5000000000 wei.

```shell
curl --data '{"jsonrpc": "2.0", "id": 0, "method": "parity_minGasPrice"}' -H "Content-Type: application/json" -X POST localhost:8545
```

```json
{"jsonrpc":"2.0","result":"0x250e87c","id":0}
```

I've never programmed in Rust, but looking at the [source code of the error](https://github.com/paritytech/parity-ethereum/blob/d5c19f8719dbcaeabafe1ed99cd0486c52ea0c48/rpc/src/v1/helpers/errors.rs#L396) and the [default option](https://github.com/paritytech/parity-ethereum/blob/d89b8d904ff28382d3692290a936706304627255/miner/src/pool/verifier.rs#L40), it looks like maybe the option is never getting set, or maybe there's some printing floating point error?

**Comment by dtran320** [comment]
Please let me know if any other details would be useful here! It looks like we may only be seeing this on nodes with `--pruning=archive`.

**Comment by nikilster** [comment]
@joshua-mir any update on this - we're having customers run into this issue!

**Comment by th3m477** [comment]
Hi - Surprised this hasn't been addressed by anyone yet, it's quite a constant issue. Any help appreciated 👍

**Comment by seunlanlege** [comment]
I think this issue is more likely to be caused by duplicate transactions being submitted to the tx queue with the same gas price and the error message doesn't communicate that.

**Comment by dtran320** [comment]
Still seeing this in `2.5.5-stable` and on nodes without `pruning=archive` this time.
