### ISSUE TITLE
2.5.8 and 2.5.9 reject all rinkeby peers with "Wrong network", never start sync

### ISSUE THREAD

**Issue by c2h5oh** [paritytech/parity-ethereum#11117]
- **Parity Ethereum version**: 2.5.8-stable, 2.5.9-stable
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: rinkeby
- **Restarted**: yes

2.5.7-stable works correctly

### Expected behavior:

Parity discovers nodes and starts sync

### Actual behavior

Parity discovers nodes and rejects them with "Wrong network", sync never starts

```
2019-10-02 14:31:47 UTC Starting Parity-Ethereum/v2.5.9-stable-06c7096-20190926/x86_64-linux-gnu/rustc1.36.0
2019-10-02 14:31:47 UTC Keys path /home/parity/.local/share/io.parity.ethereum/keys/rinkeby
2019-10-02 14:31:47 UTC DB path /home/parity/.local/share/io.parity.ethereum/chains/rinkeby/db/dc9f4256f2da3f3e
2019-10-02 14:31:47 UTC State DB configuration: fast
2019-10-02 14:31:47 UTC Operating mode: active
2019-10-02 14:31:47 UTC Configured for Rinkeby using Clique engine
2019-10-02 14:31:47 UTC Listening for new connections on 127.0.0.1:8546.
2019-10-02 14:31:52 UTC Public node URL: enode://<snip>@172.17.0.2:30303
2019-10-02 14:32:22 UTC    0/25 peers   976 bytes chain   16 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-10-02 14:32:52 UTC    0/25 peers   976 bytes chain   16 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-10-02 14:33:22 UTC    0/25 peers   976 bytes chain   16 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
```

logging=debug sample:
```
2019-10-02 14:34:44 UTC main DEBUG ethcore_network_devp2p::host  Error opening key file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2019-10-02 14:34:44 UTC main DEBUG network  Listening at V4(0.0.0.0:30303)
2019-10-02 14:34:44 UTC main DEBUG network  Error opening node table file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2019-10-02 14:34:44 UTC main INFO parity_ws  Listening for new connections on 127.0.0.1:8546.
2019-10-02 14:34:44 UTC main DEBUG jsonrpc_ws_server::server  Bound to local address: 127.0.0.1:8546
2019-10-02 14:34:44 UTC  DEBUG tokio_reactor::background  starting background reactor
2019-10-02 14:34:44 UTC  DEBUG tokio_reactor::background  starting background reactor
2019-10-02 14:34:44 UTC  DEBUG tokio_reactor::background  starting background reactor
2019-10-02 14:34:45 UTC IO Worker #1 DEBUG network  Connecting peers: 0 sessions, 0 pending + 3 started
2019-10-02 14:34:45 UTC IO Worker #2 DEBUG network  Hello: Geth/v1.9.6-unstable-63b18027-20190920/linux-amd64/go1.12 v5 0x3431…7cb8 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:45 UTC IO Worker #1 DEBUG sync  1 -> Invalid packet 0
2019-10-02 14:34:46 UTC IO Worker #1 DEBUG network  Connecting peers: 0 sessions, 0 pending + 2 started
2019-10-02 14:34:47 UTC IO Worker #0 DEBUG network  Connecting peers: 0 sessions, 0 pending + 2 started
2019-10-02 14:34:48 UTC IO Worker #0 DEBUG network  Connecting peers: 0 sessions, 0 pending + 2 started
2019-10-02 14:34:49 UTC  DEBUG ethcore_network_devp2p::ip_utils  Gateway search error: IO error: Resource temporarily unavailable (os error 11)
2019-10-02 14:34:49 UTC IO Worker #0 INFO network  Public node URL: enode://fa072311437bf991c79f76af943c321ee8cb8818848fd2cd8629d8fac52694eb245be40bb200fbe73d1bc12679986b887ac3b528aa8957f9a0c0441ff90db38b@172.17.0.2:30303
2019-10-02 14:34:49 UTC IO Worker #0 DEBUG network  Connecting peers: 0 sessions, 0 pending + 2 started
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG network  Connecting peers: 0 sessions, 0 pending + 32 started
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-content-damocles-4aa88705/linux-amd64/go1.12 v5 0xda03…cc04 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG network  Hello: Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0 v5 0x6576…5ec8 [SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG sync  1 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: Getc/v6.0.8/linux/go1.12.7 v4 0xdfed…ede4 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG sync  22 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-premium-damocles-4aa88705/linux-amd64/go1.12 v5 0xbabc…6b86 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: Geth/v0.4.2-akroma-b00f8ca4/linux-amd64/go1.11.1 v5 0x4829…169e [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG sync  25 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG network  Hello: Geth/v1.2.1-Ether1_MN_SN-Robin-Hood-23688bc6/linux-amd64/go1.12 v5 0xee9d…1a29 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG sync  26 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: REOSC/v2.2.3-unstable-6bcba06-20190321/x86_64-linux-gnu/rustc1.37.0 v5 0xdefb…bc37 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG network  Hello: Geth/v1.9.2-stable-e76047e9/linux-amd64/go1.12.7 v5 0x9dc9…e5c6 []
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG network  Hello: gtan/ByzantineLab9/v1.8.27-stable-21147d8d/linux-amd64/go1.12.7 v5 0xc517…bca2 []
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG sync  21 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #0 DEBUG network  Hello: Geth/v3.0.1-stable-691938d4/linux-amd64/go1.10.3 v5 0x2bfd…2c79 []
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: egem/v1.1.1-onoskelis-0a846937/linux-amd64/go1.12 v5 0x3e97…d991 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-content-damocles-4aa88705/linux-amd64/go1.12 v5 0x6be1…c273 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: Geth/v1.9.0-unstable-10b170d6/linux-amd64/go1.10.4 v5 0x9fc4…5fc3 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG sync  31 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #1 DEBUG network  Hello: Parity-Ethereum/v2.2.10-stable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.32.0 v5 0x3708…8ae2 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG sync  16 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG sync  23 -> Invalid packet 0
2019-10-02 14:34:50 UTC IO Worker #2 DEBUG network  Hello: Geth/v1.8.17-unstable-e39a9b34/linux-amd64/go1.11 v5 0xed37…5253 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG network  Hello: Gvns/v2.0.1-unstable-425c18d3/linux-amd64/go1.9.3 v5 0xa079…7e3c []
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG sync  27 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG discovery  Removing expired PING request for node_id=0xcf90d15f5c5cfd74a3b914b358b350e563b4135c07e1c8c796c681e6ff111729f2783bf9c3105b5bc32ce2351ccd710e10c60583b063ad4890d21133c7d36132
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG discovery  Removing expired PING request for node_id=0x0158f7585deb01c4eac5898ece3c3e007258ba382fce799327556f59842a5c8c5c803284fa155d8159e0fc9a65a587c6ebd03563685ced9f88941a7c3f3cfc38
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG discovery  Got unexpected Pong from V4(157.245.93.35:50000) ; request not found
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG network  Connecting peers: 0 sessions, 0 pending + 32 started
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-premium-damocles-4aa88705/linux-amd64/go1.12 v5 0x33e1…f8df [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG sync  10 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #1 DEBUG network  Hello: Gubiq/v2.1.0-lit-24eb94fc/linux-amd64/go1.11.1 v4 0xe68e…6710 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-premium-damocles-4aa88705/linux-amd64/go1.12 v5 0x19bc…aa85 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG network  Hello: Gubiq/v2.0.1-uip1-f983a239/linux/go1.11.1 v4 0x1971…8df4 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG network  Hello: Pirl/v1.8.27-v6-masternode-premium-damocles-4aa88705/linux-amd64/go1.12 v5 0xa8eb…e99b [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Hello: besu/v1.2.5-dev-2fbdbabb/linux-x86_64/oracle_openjdk-java-11 v5 0x98f6…316d [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Disconnected: 9: TooManyPeers
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG sync  Error sending status request: Error(Expired, State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x55755396e48d - <no info>
   1:     0x5575537423fc - <no info>
   2:     0x557552fdef6d - <no info>
   3:     0x557552f9caac - <no info>
   4:     0x557552f9ce06 - <no info>
   5:     0x557552ec7098 - <no info>
   6:     0x557552fb0717 - <no info>
   7:     0x557552fd422b - <no info>
   8:     0x557552fd641c - <no info>
   9:     0x557552f97ae9 - <no info>
  10:     0x557552f949fe - <no info>
  11:     0x5575539cc25e - <no info>
  12:     0x5575539cedeb - <no info>
  13:     0x7f94cf2016b9 - <no info>
  14:     0x7f94ced2141c - <no info>
  15:                0x0 - <no info>) } })
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG sync  19 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG network  Hello: Geth/v0.4.2-akroma-b00f8ca4/linux-amd64/go1.11.1 v5 0x649e…5ea1 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG sync  29 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Hello: Parity-Ethereum/v2.5.5-stable-3ebc769-20190708/x86_64-linux-gnu/rustc1.36.0 v5 0xdd60…94f2 [SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 16 }]
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG network  Hello: Parity-Ethereum/v2.4.5-stable-76d4064-20190408/x86_64-linux-gnu/rustc1.33.0 v5 0xa239…6ad6 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Hello: REOSC/v2.2.3-unstable-6bcba06-20190321/x86_64-linux-gnu/rustc1.37.0 v5 0x93d6…aaa0 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG sync  31 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Hello: Parity-Ethereum/v2.2.10-stable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.32.0 v5 0x63fc…7c72 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG sync  15 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG discovery  Got unexpected Pong from V4(157.245.93.35:50000) ; request not found
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG network  Hello: Parity-Ethereum/v2.2.10-stable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.32.0 v5 0x7d66…51b0 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG network  Hello: Parity-Ethereum/v2.2.10-stable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.32.0 v5 0x6c3d…bf20 [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG network  Hello: Parity-Ethereum/testnoedli/v2.2.10-stable-7b1d3e1-20190213/x86_64-linux-gnu/rustc1.32.0 v5 0x4313…1a9b [SessionCapabilityInfo { protocol: [101, 116, 104], version: 63, packet_count: 17, id_offset: 16 }, SessionCapabilityInfo { protocol: [112, 97, 114], version: 3, packet_count: 24, id_offset: 33 }, SessionCapabilityInfo { protocol: [112, 105, 112], version: 1, packet_count: 9, id_offset: 57 }]
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0x0c79c59e88b8e78fc97b6f75a52686a2e63aa2518eacc4a56deb8591fa2dba310076070f84f25c63a18365e25029638f360fd030706e81fa438760aaac6d75a2
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0xcf90d15f5c5cfd74a3b914b358b350e563b4135c07e1c8c796c681e6ff111729f2783bf9c3105b5bc32ce2351ccd710e10c60583b063ad4890d21133c7d36132
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0x2a8cbc3d12db9cd07e65c74d9a0e7a5580079299f31c239fe538849320c339198fabb8d3233e418bcf83df4270b1ba39b753c4f6ddf6a3d4533e6bc143471df2
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0x5a4c7c4ff97fb2a797874171d4339785bab06cde6e0c8da25d7cd94e3251edd0b0a8642acf4a52af06b8181cbe2f91a598373ef6b8682a8fb5cec434b4ebdfe3
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0x0158f7585deb01c4eac5898ece3c3e007258ba382fce799327556f59842a5c8c5c803284fa155d8159e0fc9a65a587c6ebd03563685ced9f88941a7c3f3cfc38
2019-10-02 14:34:51 UTC IO Worker #2 DEBUG discovery  Removing expired PING request for node_id=0x1af40358235b4efba81848fbdb9c1ac67a20f5f648eb53a15e545be7c0b964d8d57f74117dd85139fb5eb974ab66c447bf70dec3223dca3af44e899eb35d1317
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG pip  Disabling peer 7: Wrong network
2019-10-02 14:34:51 UTC IO Worker #3 DEBUG sync  7 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG sync  20 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG sync  17 -> Invalid packet 0
2019-10-02 14:34:51 UTC IO Worker #0 DEBUG pip  Disabling peer 17: Wrong network
````

### Steps to reproduce

1. `docker run parity/parity:v2.5.9-stable --chain=rinkeby` or `docker run parity/parity:v2.5.8-stable --chain=rinkeby`
2. wait for a bit

2.5.6 and 2.5.7 work.

**Comment by joshua-mir** [comment]
Hey, thanks for the report, we're aware of the issue and it's already resolved in #11108 which will be in the next release - as you've already noticed prior versions already work.

**Comment by luosprz** [comment]
Any news to release a version with this fixed issue?

**Comment by joshua-mir** [comment]
@luosprz yes, it's already backported to the beta and stables branches pending release

**Comment by andy-mcewan-artos-io** [comment]
What date is the next release expected? If anything goes wrong and users have to sync from scratch that seems to take a few days at the minute, so can you ensure this goes in well before the Istanbul block is expected on Rinkeby?

**Comment by c2h5oh** [comment]
TBH I expected having support for one of of the testnets completely broken would warrant a hotfix release, but this has been broken for over 7 weeks, fix has been merged 5 weeks ago and yet nothing..

**Comment by valer-cara** [comment]
In the meantime, one can simply use the chainspec here: https://raw.githubusercontent.com/paritytech/parity-ethereum/bd4f7922cb7590b78194cf24eb09fbfcd1f2ad69/ethcore/res/ethereum/rinkeby.json

**Comment by joshua-mir** [comment]
can anyone confirm that you still can't sync with a peer that is known to be on the correct fork (perhaps add it to a reserved_peers file?) on the latest releases (2.5.10, 2.6.5)?

**Comment by valer-cara** [comment]
I was running 2.5.9 - didn't realise the update was out.
Just switched to 2.5.10 and it's all good using only `--chain=rinkeby`. I've dropped using the full chainspec as stated above. :raised_hands:

**Comment by joshua-mir** [comment]
alright, closing this issue for now
